fil1 = input("Enter the 1st file name: ")
fil2 = input("Enter the 2nd file name: ")

samp1 = open(fil1, "r")
samp2 = open(fil2, "r")
print(f"{samp1}\n{samp2}")
samp1.close()
samp2.close()
samp1 = open(fil1, "a")
samp2 = open(fil2, "r")
reader = samp2.read()
samp1.write(reader)
print(f"{samp1}\n{samp2}")
samp1.close()
samp2.close()