file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "r")
print(file.read())
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "r")
print(file.read(10))
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "r")
print(file.readline())
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "r")
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "r")
print(file.readlines())
file.close()