sample = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "r")
print(sample.read())
sample.close()
sample = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "w")
sample.write("You have slowed down to 100kmph.")
sample.write("You have evaporated into fine atoms.")
sample.close()
sample = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson1\sample.txt", "a")
sample.write("You have survived because Thanos snapped his fingers.")
sample.close()