cod = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\codingal.txt", "r")
swi = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\switched.txt", "r")
ran = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\ile3.txt", "x")
ran.close()
ran = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\ile3.txt", "w")
codcode = cod.read()
swicode = swi.read()
ran.write(codcode)
ran.write(swicode)
cod.close()
swi.close()
ran.close()