import os
copy = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\iseless.txt", "x")
cod = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\codingal.txt", "r")
swi = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\switched.txt", "r")
copy.close()
copy = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\iseless.txt", "w")
codcode = cod.read()
copy.write(codcode)
cod.close()
cod = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\codingal.txt", "w")
swicode = swi.read()
cod.write(swicode)
copy.close()
copy = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\iseless.txt", "r")
copycode = copy.read()
swi.close()
swi = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\switched.txt", "w")
swi.write(copycode)
swi.close()
cod.close()
copy.close()
os.remove("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson3\iseless.txt")