li = ["banana", "apple", "papaya", "orange", "strawberry"]
print(len(li))
print(li[0])
print(li[-1])
print(li)
li.append("blueberry")
print(li)
li.remove("papaya")
print(li)
li.sort()
print(li)
li.pop(-1)
print(li)
li.reverse()
print(li)
print(li * 2)
print(li[1:-1])
li.clear()
print(li)