file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\Codingal.txt", "r")
print(file.read())
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\Codingal.txt", "w")
file.write("The next line is false.\nThe previous line is true.")
file.write("\nIf python is ur power, what are you without it?")
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\Codingal.txt", "a")
file.write("\nQuoted by none")
file.close()