file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\sile.txt", "r")
print(file.read())
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\sile.txt", "w")
file.write("I am writing in the file.")
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\sile.txt", "r")
print(file.read())
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\sile.txt", "a")
file.write("\nI am appending this file.")
file.close()
file = open("C:\Deekshith\DeekPython\Python\DeepLearning\Module3\Lesson2\sile.txt", "r")
print(file.read())
file.close()
